### ISSUE TITLE
Document that Toolchains have oved to DevOps

### ISSUE THREAD

**Issue by tom342178** [IBM-Bluemix-Docs/ContinuousDelivery#12]
I used to be able to access the toolchains directly from the Continuous Delivery Service. If we are not going to provide a link on the UI, then we should at a minimum highlight it at the top of the documentation.

**Comment by acolleen** [comment]
Thank you for your feedback. I've discussed this with our development team and there is currently an open issue for development to add a link to the Continuous Delivery user interface for users to access the toolchains directly. 

In the meantime, I've added a Tip in the introductory section of the Continuous Delivery "Getting started tutorial" to help users until the UI update is available:
https://cloud.ibm.com/docs/services/ContinuousDelivery?topic=ContinuousDelivery-cd_getting_started#cd_getting_started
