### ISSUE TITLE
Live Sync Debug - Possible troubleshooting content

### ISSUE THREAD

**Issue by christx83** [IBM-Bluemix-Docs/ContinuousDelivery#14]
We've been scrubbing the troubleshooting topic in the `docs/apps` repo and came across this content that probably fits better in the `docs/ContinuousDelivery` repo. I don't know how long this content has existed (it was there before I joined the team in July last year).

Would you like to have someone in your team review it to ensure that it's still applicable and correct? I'm removing it from the "Creating apps" troubleshooting topic.

Here's the content in MD format:

## {{site.data.keyword.cloud_notm}} Live Sync Debug doesn't start from the command line
{: #ts_no_debug}
{: troubleshoot}

You enabled the {{site.data.keyword.cloud_notm}} Live Sync Debug feature for your app by using the command line, but you can't access the Debug interface.

You enabled the Debug feature for your app by setting the **BLUEMIX_APP_MGMT_ENABLE** environment variable. However, you can't access the Debug user interface at `app_url/bluemix-debug/manage`.
{: tsSymptoms}

The Debug feature can't be enabled in these situations:
{: tsCauses}

  * When the `manifest.yml` contains the command attribute
  * When you use the **-c** option to push an app to {{site.data.keyword.cloud_notm}}

Use one of the following options to resolve the issue:
{: tsResolve}

  * The recommended practice is to use the IBM Node.js buildpack to start the app. For more information, see the Startup command section of the [Deploying a Node.js application to {{site.data.keyword.cloud_notm}}](/docs/runtimes/nodejs?topic=Nodejs-startup_commmand#startup_commmand) topic.
  * Disable the command for your existing app either by revising the command attribute in your `manifest.yml` to command: null or by editing your push command to include `-c null`.
  * Remove the **command** attribute from the `manifest.yml`. Then, delete the current app from {{site.data.keyword.cloud_notm}} and push the app again.

**Comment by acolleen** [comment]
@christx83 thanks for letting me know about this content. I've created the following issue to work with the Continuous Delivery dev and determine whether the Live Edit troubleshooting content is still valid (and should be added to the CD docs).

https://github.ibm.com/org-ids/ua-issues/issues/1024

**Comment by acolleen** [comment]
Closing this since dev reviewed the content and determined that it no longer applies.

**Comment by christx83** [comment]
Thank you for checking on this, @acolleen!
