### ISSUE TITLE
translated deploy to cloud buttons use bluemix, not ibm cloud

### ISSUE THREAD

**Issue by stevemart** [IBM-Bluemix-Docs/ContinuousDelivery#15]
There's a line in https://cloud.ibm.com/docs/services/ContinuousDelivery?topic=ContinuousDelivery-deploy-button that references translated images:

```
If you want to use a translated version of the button, you can reference it remotely
or download it from ftp://public.dhe.ibm.com/cloud/bluemix/deploy_button
```

When looking at that location (ftp://public.dhe.ibm.com/cloud/bluemix/deploy_button) all the images say "Bluemix", not "IBM Cloud". Attaching a few here... Would recommend removing that line while images are updated.

![button_en](https://user-images.githubusercontent.com/4118756/57721889-48f6ae80-7653-11e9-94e4-8c267768bf8d.png)
![button_ko](https://user-images.githubusercontent.com/4118756/57721890-48f6ae80-7653-11e9-9c9c-99047d0f89d8.png)
![button_white_pt_BR](https://user-images.githubusercontent.com/4118756/57721891-48f6ae80-7653-11e9-9a8a-9cda1efb64f9.png)

**Comment by acolleen** [comment]
This issue is being tracked here:
https://github.ibm.com/org-ids/ua-issues/issues/986

In the meantime, I've removed the line that references the translated images from the docs.
