### ISSUE TITLE
Stage Properties tip is misleading

### ISSUE THREAD

**Issue by davesteinberg** [IBM-Bluemix-Docs/ContinuousDelivery#16]
In https://cloud.ibm.com/docs/services/ContinuousDelivery?topic=ContinuousDelivery-deliverypipeline_about&origin_team=T18EL2249#stage-properties, the tip about passing environment properties between jobs is ambiguous.

I interpreted it as describing an *alternative* to defining stage properties in the UI, so I thought that if you export environment variables they will be available in subsequent jobs, without having to define them in the UI first. That didn't work. It was then explained to me that, no, you always have to define them in the UI. Perhaps something like this would be more clear:

> You can define a stage property with an initial value (or a blank value) and then override the initial value in a job by exporting an environment variable, so that subsequent jobs in the stage will see that new value. For example, you can include the following command to set the $API_KEY property and make it available to another job: `export API_KEY=<insert API key here>`

**Comment by acolleen** [comment]
Thanks for your feedback. I've updated the Tip to reflect your suggestions:
https://cloud.ibm.com/docs/services/ContinuousDelivery?topic=ContinuousDelivery-deliverypipeline_about#stage-properties
