### ISSUE TITLE
Replace use of "Bluemix services" in Catalog page feature description ... IBM Cloud now

### ISSUE THREAD

**Issue by nubbyOne** [IBM-Bluemix-Docs/ContinuousDelivery#17]
Replace use of "Bluemix services" in Tool Chains Catalog page description ... Bluemix doesn't exist ... it's IBM Cloud now.

Go here:
https://cloud.ibm.com/catalog/services/continuous-delivery

<img width="1671" alt="Screen Shot 2019-08-14 at 1 21 56 PM" src="https://user-images.githubusercontent.com/11412634/63041914-e94cb100-be96-11e9-8f83-634bda4a89cd.png">

**Comment by acolleen** [comment]
Thank you for reporting this. I've communicated this issue to Development so that they can update this text in the CD Catalog UI.

**Comment by acolleen** [comment]
The following Development issue is now tracking this work:
https://github.ibm.com/org-ids/roadmap/issues/10105
