### ISSUE TITLE
Mentions of container service

### ISSUE THREAD

**Issue by kKronstainBrown** [IBM-Bluemix-Docs/ContinuousDelivery#4]
I think that the stuff that is listed as applying to the container service in here is no longer applicable with the Kubernetes version of the container service: 
https://github.com/IBM-Bluemix-Docs/ContinuousDelivery/blob/master/deliverypipeline_extension.md

And in here, you can use the deploy button with the Kubernetes version of the service, but you must have a cluster to deploy the app into first.
https://github.com/IBM-Bluemix-Docs/ContinuousDelivery/blob/master/deploy_button.md

**Comment by acolleen** [comment]
For tracking purposes, I created the following issue for this in our CD ua-issues repo:
https://github.ibm.com/org-ids/ua-issues/issues/634

**Comment by acolleen** [comment]
Closing since we're using this issue in the CD ua-issues repo to track work on this (Hadar is looking at it):
https://github.ibm.com/org-ids/ua-issues/issues/634
